### ISSUE TITLE
git.yazi plugin, THEME.git.modified = ui.Style():fg() color can not be setup

### ISSUE THREAD

**Issue by ovwxxwvo** [yazi-rs/plugins#32] opened 2024-11-18 12:31 UTC
### `yazi --debug` output

```Shell
Yazi
    Version: 0.3.3 (Arch Linux 2024-09-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("tmux-256color", "tmux")
    Emulator.via_csi: Ok(Unknown([]))
    Emulator.detect : Unknown([])

Adapter
    Adapter.matches: Wayland

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : None
    SWAYSOCK                   : Some("/run/user/1000/sway-ipc.1000.150012.sock")
    HYPRLAND_INSTANCE_SIGNATURE: None
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/bash")
    EDITOR             : Some("nvim")
    VISUAL             : None
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })
    block  : Some(Opener { run: "nvim \"$@\"", block: true, orphan: false, desc: "nvim", for_: None, spread: true })

Multiplexers
    TMUX               : true
    tmux version       : tmux 3.5a
    ZELLIJ_SESSION_NAME: None
    Zellij version     : No such file or directory (os error 2)

Dependencies
    file             : 5.45
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: 2.2.3
    magick           : 7.1.1-40
    fzf              : 0.55.0
    fd               : 10.2.0
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : No such file or directory (os error 2)
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1


--------------------------------------------------
When reporting a bug, please also upload the `yazi.log` log file - only upload the most recent content by time.
You can find it in the "/home/oo/.local/state/yazi" directory.
```

### Please describe the problem you're trying to solve

after plugin download & setup, symbol setup work but color setup not.
the default config method can not setup the color, & I modified the plugin.
```shell
ya pack -a yazi-rs/plugins:git
require("git"      ):setup()
```

symbol setup work,
```lua
THEME.git = THEME.git or {}
THEME.git.modified_sign  = "*"
THEME.git.added_sign     = "+"
THEME.git.deleted_sign   = "-"
THEME.git.updated_sign   = "^"
THEME.git.ignored_sign   = "~"
THEME.git.untracked_sign = "?"
```

color setup doesn't work,
```lua
THEME.git = THEME.git or {}
-- print(Style)
THEME.git.modified       = ui.Style():fg("#b08050")
THEME.git.added          = ui.Style():fg("#8050b0")
THEME.git.deleted        = ui.Style():fg("#b05080")
THEME.git.untracked      = ui.Style():fg("#808080")
THEME.git.updated        = ui.Style():fg("#50b0b0")
THEME.git.ignored        = ui.Style():fg("#80b050")
```

### Would you be willing to contribute this feature?

- [X] Yes, I'll give it a shot

### Describe the solution you'd like

rewrite the `git.lua` -> fn `setup` -> struct `styles`, & set some global var.
```lua
local t = THEME.git or {}
local git_modified_fg  = t.modified_fg  or "#ffa500"
local git_added_fg     = t.added_fg     or "#32cd32"
local git_deleted_fg   = t.deleted_fg   or "#ff4500"
local git_updated_fg   = t.updated_fg   or "#1e90ff"
local git_ignored_fg   = t.ignored_fg   or "#696969"
local git_untracked_fg = t.untracked_fg or "#a9a9a9"

local styles = {
	[6] = t.modified  and ui.Style(t.modified)  or ui.Style():fg(git_modified_fg ),
	[5] = t.added     and ui.Style(t.added)     or ui.Style():fg(git_added_fg    ),
	[2] = t.deleted   and ui.Style(t.deleted)   or ui.Style():fg(git_deleted_fg  ),
	[1] = t.updated   and ui.Style(t.updated)   or ui.Style():fg(git_updated_fg  ),
	[3] = t.ignored   and ui.Style(t.ignored)   or ui.Style():fg(git_ignored_fg  ),
	[4] = t.untracked and ui.Style(t.untracked) or ui.Style():fg(git_untracked_fg),

	-- [6] = t.modified  and ui.Style(t.modified)  or ui.Style():fg("#ffa500"),
	-- [5] = t.added     and ui.Style(t.added)     or ui.Style():fg("#32cd32"),
	-- [2] = t.deleted   and ui.Style(t.deleted)   or ui.Style():fg("#ff4500"),
	-- [1] = t.updated   and ui.Style(t.updated)   or ui.Style():fg("#1e90ff"),
	-- [3] = t.ignored   and ui.Style(t.ignored)   or ui.Style():fg("#696969"),
	-- [4] = t.untracked and ui.Style(t.untracked) or ui.Style():fg("#a9a9a9"),
}
```

the format of the config file will be like this,
```lua
THEME.git = THEME.git or {}
  -- print(Style)
  -- THEME.git.modified       = ui.Style():fg("#b08050")
  -- THEME.git.added          = ui.Style():fg("#8050b0")
  -- THEME.git.deleted        = ui.Style():fg("#b05080")
  -- THEME.git.untracked      = ui.Style():fg("#808080")
  -- THEME.git.updated        = ui.Style():fg("#50b0b0")
  -- THEME.git.ignored        = ui.Style():fg("#80b050")

THEME.git.modified_fg    = "#b08050"
THEME.git.added_fg       = "#8050b0"
THEME.git.deleted_fg     = "#b05080"
THEME.git.updated_fg     = "#50b0b0"
THEME.git.ignored_fg     = "#80b050"
THEME.git.untracked_fg   = "#808080"

THEME.git.modified_sign  = "*"
THEME.git.added_sign     = "+"
THEME.git.deleted_sign   = "-"
THEME.git.updated_sign   = "^"
THEME.git.ignored_sign   = "~"
THEME.git.untracked_sign = "?"
```

### Additional context

whole setup fn,
```lua
local function setup(st, opts)
	st.dirs = {}
	st.repos = {}
	opts = opts or {}
	opts.order = opts.order or 1500
	-- Chosen by ChatGPT fairly, PRs are welcome to adjust them

	local t = THEME.git or {}
  local git_modified_fg  = t.modified_fg  or "#ffa500"
  local git_added_fg     = t.added_fg     or "#32cd32"
  local git_deleted_fg   = t.deleted_fg   or "#ff4500"
  local git_updated_fg   = t.updated_fg   or "#1e90ff"
  local git_ignored_fg   = t.ignored_fg   or "#696969"
  local git_untracked_fg = t.untracked_fg or "#a9a9a9"
    -- local git_modified_fg
    -- local git_added_fg
    -- local git_deleted_fg
    -- local git_updated_fg
    -- local git_ignored_fg
    -- local git_untracked_fg

	local styles = {
		[6] = t.modified  and ui.Style(t.modified)  or ui.Style():fg(git_modified_fg ),
		[5] = t.added     and ui.Style(t.added)     or ui.Style():fg(git_added_fg    ),
		[2] = t.deleted   and ui.Style(t.deleted)   or ui.Style():fg(git_deleted_fg  ),
		[1] = t.updated   and ui.Style(t.updated)   or ui.Style():fg(git_updated_fg  ),
		[3] = t.ignored   and ui.Style(t.ignored)   or ui.Style():fg(git_ignored_fg  ),
		[4] = t.untracked and ui.Style(t.untracked) or ui.Style():fg(git_untracked_fg),
		-- [6] = t.modified  and ui.Style(t.modified)  or ui.Style():fg("#ffa500"),
		-- [5] = t.added     and ui.Style(t.added)     or ui.Style():fg("#32cd32"),
		-- [2] = t.deleted   and ui.Style(t.deleted)   or ui.Style():fg("#ff4500"),
		-- [1] = t.updated   and ui.Style(t.updated)   or ui.Style():fg("#1e90ff"),
		-- [3] = t.ignored   and ui.Style(t.ignored)   or ui.Style():fg("#696969"),
		-- [4] = t.untracked and ui.Style(t.untracked) or ui.Style():fg("#a9a9a9"),
	}
	local signs = {
		[6] = t.modified_sign and t.modified_sign or "",
		[5] = t.added_sign and t.added_sign or "",
		[4] = t.untracked_sign and t.untracked_sign or "",
		[3] = t.ignored_sign and t.ignored_sign or "",
		[2] = t.deleted_sign and t.deleted_sign or "",
		[1] = t.updated_sign and t.updated_sign or "U",
	}

	Linemode:children_add(function(self)
		local url = self._file.url
		local dir = st.dirs[tostring(url:parent())]
		local change
		if dir then
			change = dir == "" and 3 or st.repos[dir][tostring(url):sub(#dir + 2)]
		end

		if not change or signs[change] == "" then
			return ui.Line("")
		elseif self._file:is_hovered() then
			return ui.Line { ui.Span(" "), ui.Span(signs[change]) }
		else
			return ui.Line { ui.Span(" "), ui.Span(signs[change]):style(styles[change]) }
		end
	end, opts.order)
end
```

### Validations

- [X] I have searched the existing issues/discussions

**Comment by sxyazi** [comment] 2024-11-18 12:37
No debug info

**Comment by ovwxxwvo** [comment] 2024-11-18 12:46
> No debug info

the plugin has a default color, but  can not be set by the way you mentioned.

**Comment by ovwxxwvo** [comment] 2024-11-18 12:54
@sxyazi hey, I'm little bit tired,
where should I put the plugins I'm going to write? & where should I promote them?
I will write a `flavor` for yazi. Hope the structure of the config file can be better.

**Comment by ovwxxwvo** [comment] 2024-11-18 13:12
> No debug info

mistake. I thought it was unnecessary.

**Comment by sxyazi** [comment] 2024-11-18 13:17
>     Version: 0.3.3 (Arch Linux 2024-09-05)

You're not using the nightly version, the changing color feature needs nightly atm, already mentioned in the README:

![screenshot-002138](https://github.com/user-attachments/assets/1265045b-c06d-454a-bc5d-bfdcbc94b62c)

Closing as expected behavior

**Closed by sxyazi** 2024-11-18 13:17 UTC
Labels: feature

**Comment by ovwxxwvo** [comment] 2024-11-18 13:56
unbelievable

**Comment by ovwxxwvo** [comment] 2024-11-18 14:28
@sxyazi hey, do not consider about my code. 
the config file looks more consistent in this way.
I will still do it in my way.

**Comment by lpnh** [comment] 2024-11-18 15:34
> > > ```
> > > Version: 0.3.3 (Arch Linux 2024-09-05)
> > > ```
> > 
> > 
> > You're not using the nightly version, the changing color feature needs nightly atm, already mentioned in the README:
> > ![screenshot-002138](https://private-user-images.githubusercontent.com/17523360/387230077-1265045b-c06d-454a-bc5d-bfdcbc94b62c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MzczMTUsIm5iZiI6MTczMTkzNzAxNSwicGF0aCI6Ii8xNzUyMzM2MC8zODcyMzAwNzctMTI2NTA0NWItYzA2ZC00NTRhLWJjNWQtYmZkY2JjOTRiNjJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDEzMzY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MTJiNzQzNTY4NjMzNTNhMTRjMTFjZDcwZmFiYWZiZTQ5YzM0ZjQ5YmI1MDdjMDE0ZWJlMTA5ODdlZDM1NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FAvri01lmGv72uUEYFFfX2WdcZkUTUBewMYB4cVYrlw)
> > Closing as expected behavior
> 
> what this `nightly atm`.

The root of the issue here is that you are trying to use a feature that is not available in your current version of Yazi. A nightly build is a development version that is updated daily with the latest changes. Here's a [Wikipedia article about it](https://en.wikipedia.org/wiki/Daily_build).

You can find the Yazi nightly release [here](https://github.com/sxyazi/yazi/releases/tag/nightly).
Since you are using Arch, there’s a package for the nightly version available on AUR called [yazi-nightly-bin](https://aur.archlinux.org/packages/yazi-nightly-bin).

As a side note, I understand that dealing with unresolved issues can sometimes be frustrating. However, I would like to kindly remind you to be mindful when interacting with the repository and the community in official channels. For example, make sure to provide all necessary information, keep your comments relevant and on-topic, and, most importantly, be respectful and polite. This helps nurture a positive and healthy environment. I truly appreciate your efforts and understanding.

**Comment by ovwxxwvo** [comment] 2024-11-18 16:04
@lpnh hey, thanks about `nightly`, just knew it few minute before.
Still act like child. Hope I will be polite.
